### ISSUE TITLE
那个谁艾特我 是什么插件

### ISSUE THREAD

**Issue by duoshoumiao** [RSRH-Rs/image_lssv#1]
那个谁艾特我 是什么插件

**Comment by RSRH-Rs** [comment]
还在测试，过两天发出来

**Comment by RSRH-Rs** [comment]
> 那个谁艾特我 是什么插件

对了，如果你们还有想要的插件可以提一提，因为我不知道群友想要什么功能😊

**Comment by duoshoumiao** [comment]
> > 那个谁艾特我 是什么插件
> 
> 对了，如果你们还有想要的插件可以提一提，因为我不知道群友想要什么功能blush
公主连结wiki。 下面那个wiki想更新 更新不了了，能有个链接b站的wiki也行

**Comment by RSRH-Rs** [comment]
> > > 那个谁艾特我 是什么插件
> > 
> > 对了，如果你们还有想要的插件可以提一提，因为我不知道群友想要什么功能blush
> 公主连结wiki。 下面那个wiki想更新 更新不了了，能有个链接b站的wiki也行

忙完我尽量看看（虽然我不玩公主连结

**Comment by duoshoumiao** [comment]
> > > > 那个谁艾特我 是什么插件
> > > 
> > > 
> > > 对了，如果你们还有想要的插件可以提一提，因为我不知道群友想要什么功能blush
> > > 公主连结wiki。 下面那个wiki想更新 更新不了了，能有个链接b站的wiki也行
> 
> 忙完我尽量看看（虽然我不玩公主连结
👌
