### ISSUE TITLE
代码逻辑应该有一点问题

### ISSUE THREAD

**Issue by Rinco304** [RSRH-Rs/image_lssv#5]
在多个群使用此功能时，如果一个群的服务开启情况未改变，再次获取服务列表时因为img文件夹中只存在一个`config.png`，而在`previous_services_data.json`中此群的服务列表没有改变，导致`_init_.py`中
```
if previous_services_data == svs_list and os.path.exists(
        get_path("data", "imgs", "config.png")
    ):
        await session.finish(
            MessageSegment.image("file:///" + images_path + "/config.png")
        )
```
这里直接返回了`config.png`，若此时的`config.png`是其他群在使用时生成的，会导致发出来的图片不是这个群的功能列表而是另一个群的功能列表
实际情况如图(两个群先后使用此功能，未改变功能开启与关闭的情况，此时开启了随机背景，但是`config.png`未改变而是直接发出了上一个群的配置图)：
![image](https://user-images.githubusercontent.com/75192177/235888894-331ef276-80e0-42d5-bb2d-e252db9ebecf.png)
**个人的解决方法**：在生成`config.png`时在文件名后加上群号再进行判断，这样可以避免发送其他群的服务
![image](https://user-images.githubusercontent.com/75192177/235890719-67284de1-0c00-4e29-b362-46b4b1cc33e4.png)
顺便还有一个小问题：**开启 关闭** 触发词与[https://github.com/KimigaiiWuyi/GenshinUID](url)中的**开启 关闭**有冲突，我的bot里两个都装了在开关模块时这两个都会触发，所以个人将这两个触发词去掉了

**Comment by Rinco304** [comment]
#6 这里pr了自己修改的部分（有一点是个人需求的更改：**去掉开启 关闭** 触发词）大佬可以参考pr来修改代码或者合并代码

**Comment by RSRH-Rs** [comment]
去掉了开启关闭关键词的话就控制不了服务的开关了

**Comment by RSRH-Rs** [comment]
嗯好的，但是去掉了开启关闭关键词没必要，只是个触发别名（貌似wuyi佬的开启关闭需要加gs前缀？），我使用的过程中也出现了这个问题也是想拿群名来命名（

**Comment by Rinco304** [comment]
> 嗯好的，但是去掉了开启关闭关键词没必要，只是个触发别名（貌似wuyi佬的开启关闭需要加gs前缀？），我使用的过程中也出现了这个问题也是想拿群名来命名（

确实要加，但是不加直接输入也会触发（还是返回的两条消息），我也不知道开关的是啥但总之先把它去了防止冲突（
pr中的已经去掉了，可以手动添回来_(:з」∠)_

**Comment by RSRH-Rs** [comment]
> > 嗯好的，但是去掉了开启关闭关键词没必要，只是个触发别名（貌似wuyi佬的开启关闭需要加gs前缀？），我使用的过程中也出现了这个问题也是想拿群名来命名（
> 
> 确实要加，但是不加直接输入也会触发（还是返回的两条消息），我也不知道开关的是啥但总之先把它去了防止冲突（
> pr中的已经去掉了，可以手动添回来_(:з」∠)_

哈哈哈好吧，谢谢啦
