### ISSUE TITLE
显示443应该怎么改啊

### ISSUE THREAD

**Issue by henut** [RSRH-Rs/image_lssv#7]
raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.loliapi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]
![image](https://github.com/RSRH-Rs/image_lssv/assets/57399484/deb14ee4-1f3d-46f2-863a-6693b7b616e3)

**Comment by RSRH-Rs** [comment]
发送请求那一步加个verify=False参数试试

**Comment by plumephoenix** [comment]
> verify=False

utils.py里面的请求加上个ssl=False，我试了verify=False不识别verify，还是感谢作者提供思路
