### ISSUE TITLE
突然LSSV指令就不能用

### ISSUE THREAD

**Issue by duoshoumiao** [RSRH-Rs/image_lssv#9]
能正常开关服务。图片发不出来了

**Comment by RSRH-Rs** [comment]
> 能正常开关服务。图片发不出来了

看看后台

**Comment by duoshoumiao** [comment]
![image](https://github.com/RSRH-Rs/image_lssv/assets/94856184/883ceea4-46a7-4041-8f50-38fca7ad040e)

**Comment by RSRH-Rs** [comment]
> ![image](https://github.com/RSRH-Rs/image_lssv/assets/94856184/883ceea4-46a7-4041-8f50-38fca7ad040e)
> 
> 

你这貌似都没触发指令（

**Comment by duoshoumiao** [comment]
> > ![image](https://github.com/RSRH-Rs/image_lssv/assets/94856184/883ceea4-46a7-4041-8f50-38fca7ad040e)
> > 
> > 
> 
> 你这貌似都没触发指令（

啊这  😦那怎么整

**Comment by duoshoumiao** [comment]
> > ![image](https://github.com/RSRH-Rs/image_lssv/assets/94856184/883ceea4-46a7-4041-8f50-38fca7ad040e)
> > 
> > 
> 
> 你这貌似都没触发指令（

原来需要艾特

**Comment by duoshoumiao** [comment]
破案了
